# Generated by Django 5.1.1 on 2024-10-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'verbose_name': 'Alumno', 'verbose_name_plural': 'alumnos'},
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fecha_ingreso',
            field=models.DateField(verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterModelTable(
            name='alumno',
            table='alumnos',
        ),
    ]
